/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/case.glb --types
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useStore } from './store'
import { useEffect } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Box: THREE.Mesh
    Cage: THREE.Mesh
    Handle: THREE.Mesh
    Hardware: THREE.Mesh
  }
  materials: {
    Box: THREE.MeshStandardMaterial
    Frame: THREE.MeshStandardMaterial
  }
}

export function Case() {
  const { current, color, min, max, syncMetadata } = useStore()
  const { nodes, materials } = useGLTF('/case.glb') as unknown as GLTFResult

  useEffect(() => {
    const meta = nodes.Box?.userData
    console.log(meta)

    if (meta && (meta.minWidth || meta.maxWidth)) {
      syncMetadata(
        {
          width: meta.minWidth,
          height: meta.minHeight,
          depth: meta.minDepth,
        },
        {
          width: meta.maxWidth,
          height: meta.maxHeight,
          depth: meta.maxDepth,
        }
      )
    } else {
      console.error('metadata missing')
    }
  }, [nodes, syncMetadata])

  const getInf = (current: number, min: number, max: number) => {
    // prevent division by zero
    if (!max || !min || max === min) return 0

    const influence = (current - min) / (max - min)

    // clamp to 0 - 1
    const finalValue = Math.max(0, Math.min(1, influence))
    return isNaN(finalValue) ? 0 : finalValue
  }

  const influences = [
    getInf(current.width, min.width, max.width),
    getInf(current.height, min.height, max.height),
    getInf(current.depth, min.depth, max.depth),
  ]

  return (
    <group dispose={null}>
      <group name="Case">
        <mesh
          name="Box"
          geometry={nodes.Box.geometry}
          material={materials.Box}
          morphTargetInfluences={influences}
          castShadow
        >
          <meshStandardMaterial
            map={materials.Box.map}
            color={color}
            roughness={materials.Box.roughness}
            metalness={materials.Box.metalness}
          />
        </mesh>

        <mesh
          name="Lid"
          geometry={nodes.Lid.geometry}
          material={materials.Box}
          morphTargetDictionary={nodes.Lid.morphTargetDictionary}
          morphTargetInfluences={influences}
          castShadow
        >
          <meshStandardMaterial
            map={materials.Box.map}
            color={color}
            roughness={materials.Box.roughness}
            metalness={materials.Box.metalness}
          />
        </mesh>

        <mesh
          name="Cage_Lower"
          geometry={nodes.Cage_Lower.geometry}
          material={materials.Frame}
          morphTargetDictionary={nodes.Cage_Lower.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
        <mesh
          name="Corners"
          geometry={nodes.Corners.geometry}
          material={materials.Frame}
          morphTargetDictionary={nodes.Corners.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
        <mesh
          name="Cage_Upper"
          geometry={nodes.Cage_Upper.geometry}
          material={materials.Frame}
          morphTargetDictionary={nodes.Cage_Upper.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
        <mesh
          name="Handle"
          geometry={nodes.Handle.geometry}
          material={materials.Box}
          morphTargetDictionary={nodes.Handle.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
        <mesh
          name="Handle_attach"
          geometry={nodes.Handle_attach.geometry}
          material={materials.Frame}
          morphTargetDictionary={nodes.Handle_attach.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
        <mesh
          name="Latch"
          geometry={nodes.Latch.geometry}
          material={materials.Frame}
          morphTargetDictionary={nodes.Latch.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
        <mesh
          name="Hinge"
          geometry={nodes.Hinge.geometry}
          material={materials.Frame}
          morphTargetDictionary={nodes.Hinge.morphTargetDictionary}
          morphTargetInfluences={influences}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/case.glb')