/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/case.glb --types
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useStore } from './store'
import { useEffect } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Case() {
  const { current, color, min, max, syncMetadata } = useStore()
  const { nodes, materials } = useGLTF('/case.glb') as unknown as GLTFResult

  useEffect(() => {
    const meta = nodes.Cube.userData
    syncMetadata(
      { width: meta.minWidth, height: meta.minHeight, depth: meta.minDepth },
      { width: meta.maxWidth, height: meta.maxHeight, depth: meta.maxDepth }
    )
  }, [nodes])

  const getInf = (v: number, minV: number, maxV: number) => (v - minV) / (maxV - minV)

  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        morphTargetInfluences={[
          getInf(current.width, min.width, max.width),
          getInf(current.height, min.height, max.height),
          getInf(current.depth, min.depth, max.depth),
        ]}
        castShadow
      >
        <meshStandardMaterial
          map={materials.Material.map}
          color={color}
          roughness={materials.Material.roughness}
          metalness={materials.Material.metalness}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/case.glb')