/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/case.glb --types
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useStore } from './store'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Case() {
  const { width, height, depth, color } = useStore()
  const { nodes, materials } = useGLTF('/case.glb') as unknown as GLTFResult
  const influenceW = (width - 40) / (120 - 40)
  const influenceH = (height - 10) / (50 - 10)
  const influenceD = (depth - 20) / (100 - 20)
  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        morphTargetInfluences={[influenceW, influenceH, influenceD]}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial
          map={materials.Material.map}
          color={color}
          roughness={materials.Material.roughness}
          metalness={materials.Material.metalness}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/case.glb')